language: python

sudo: false

addons:
  apt:
    packages:
    - libevent-dev

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  matrix:
    - DJANGO=Django==1.4.20
    - DJANGO=Django==1.5.12
    - DJANGO=Django==1.6.11
    - DJANGO=Django==1.7.7
    - DJANGO=Django==1.8
    - 'DJANGO="-e git+git://github.com/django/django.git#egg=Django"'
  global:
    - 'PIP_DOWNLOAD_CACHE=".pip_download_cache"'
    - 'WAD_FILES="package.json,Makefile,setup.py"'
    - 'WAD_INSTALL_COMMAND=ci/setup'

    # This should be specified with:
    # travis encrypt S3_BUCKET_NAME=secretvalue S3_CREDENTIALS=accesskey:secretkey
    # - S3_BUCKET_NAME=
    # - S3_CREDENTIALS=
    - secure: "QEFKt0HhaMlCW0FCLTz3NDY/P4UuVl1Pw8kSUVKKjbaKn2jZdaLKS68yl3Vyrd9AqrBfRNNLBAnvpZjYL6EwqqnZzpRH3KnAf0WRxE6d5ytrUkwZtOnQaN0Tumuqc3xnoXXalPXvs+abhXZpjfOzx0oPBa2WbtMF/RJZ/bwsTKE="

before_install:
  # Use closer nameservers
  # - printf "nameserver 199.91.168.70\nnameserver 199.91.168.71\n" | sudo tee /etc/resolv.conf
  # These need to be here and not in the env hash because they need to be
  # evaluated after the virtualenv has been setup
  - mkdir -p $PIP_DOWNLOAD_CACHE
  - 'export WAD_ENVIRONMENT_VARIABLES="TRAVIS_PYTHON_VERSION,TRAVIS_NODE_VERSION,WAD_CACHE_PATH"'
  - 'export WAD_CACHE_PATH="node_modules,$PIP_DOWNLOAD_CACHE,$VIRTUAL_ENV"'

install:
  - time ci/wad

script:
  - "if [[ ${TRAVIS_PYTHON_VERSION} != 'pypy' ]]; then make lint; fi"
  - py.test tests/ --cov raven --cov-report term-missing

matrix:
  allow_failures:
    - env: 'DJANGO="-e git+git://github.com/django/django.git#egg=Django"'
  exclude:
    - python: "3.2"
      env: DJANGO=Django==1.4.20
    - python: "3.3"
      env: DJANGO=Django==1.4.20
    - python: "3.4"
      env: DJANGO=Django==1.4.20
    - python: "2.6"
      env: DJANGO="-e git+git://github.com/django/django.git#egg=Django"
    - python: "3.2"
      env: DJANGO="-e git+git://github.com/django/django.git#egg=Django"
    - python: "2.6"
      env: DJANGO=Django==1.8
    - python: "2.6"
      env: DJANGO=Django==1.7.7
