language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
env:
  - DJANGO=Django==1.2.7
  - DJANGO=Django==1.3.7
  - DJANGO=Django==1.4.5
  - DJANGO=Django==1.5.1
  - DJANGO="-e git+git://github.com/django/django.git#egg=Django"

install:
  - sudo apt-get install libevent-dev
  - pip install $DJANGO --use-mirrors
  - make bootstrap
script:
  - make lint
  - py.test tests/ --cov raven --cov-report term-missing
notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=Django==1.2.7
    - python: "3.2"
      env: DJANGO=Django==1.3.7
    - python: "3.2"
      env: DJANGO=Django==1.4.5
    - python: "3.3"
      env: DJANGO=Django==1.2.7
    - python: "3.3"
      env: DJANGO=Django==1.3.7
    - python: "3.3"
      env: DJANGO=Django==1.4.5
after_success:
  - coveralls