language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
env:
  matrix:
    - DJANGO=Django==1.2.7
    - DJANGO=Django==1.3.7
    - DJANGO=Django==1.4.10
    - DJANGO=Django==1.5.5
    - DJANGO=Django==1.6
    - DJANGO="-e git+git://github.com/django/django.git#egg=Django"
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"
    - WAD_FILES="package.json,Makefile,setup.py"
    - WAD_INSTALL_COMMAND=ci/setup

    # This should be specified with:
    # travis encrypt S3_BUCKET_NAME=secretvalue S3_CREDENTIALS=accesskey:secretkey
    # - S3_BUCKET_NAME=
    # - S3_CREDENTIALS=
    - secure: pZ7DtkEu2q/pGINfVT9S+iPRE5ck6mBQmuHTQz3PVXF/UJmpM1LCbC7aqrw4GXWuUhYc50QCnMZJL1yoBORVEfY4nfXHLRc3HMoWE6Srqf0IBDywi6T+UUdLeOYe13EDb4p8WIpnRGlV4WI1WaPXuFlMEdj5tAjlC9ZotLxyVaI=
before_install:
  # Use closer nameservers
  - printf "nameserver 199.91.168.70\nnameserver 199.91.168.71\n" | sudo tee /etc/resolv.conf

  # These need to be here and not in the env hash because they need to be
  # evaluated after the virtualenv has been setup
  - mkdir -p $PIP_DOWNLOAD_CACHE
  - export WAD_ENVIRONMENT_VARIABLES="TRAVIS_PYTHON_VERSION,TRAVIS_NODE_VERSION,WAD_CACHE_PATH"
  - export WAD_CACHE_PATH="node_modules,$PIP_DOWNLOAD_CACHE,$VIRTUAL_ENV"
install:
  - time ci/wad
script:
  - "if [[ ${TRAVIS_PYTHON_VERSION} != 'pypy' ]]; then make lint; fi"
  - py.test tests/ --cov raven --cov-report term-missing
notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=Django==1.2.7
    - python: "3.2"
      env: DJANGO=Django==1.3.7
    - python: "3.2"
      env: DJANGO=Django==1.4.10
    - python: "3.3"
      env: DJANGO=Django==1.2.7
    - python: "3.3"
      env: DJANGO=Django==1.3.7
    - python: "3.3"
      env: DJANGO=Django==1.4.10
    - python: "2.6"
      env: DJANGO="-e git+git://github.com/django/django.git#egg=Django"
