language: python
sudo: false
addons:
  apt:
    packages:
      - libevent-dev
cache:
  directories:
    - "$HOME/.cache/pip"


jobs:
  fast_finish: true
#  allow_failures:
#    - python: 3.5
#      env: TOXENV=py35-django-dev-fix

  include:
    - stage: core
      python: 2.7
      env: TOXENV=py27
    - stage: core
      python: 3.3
      env: TOXENV=py33
    - stage: core
      python: 3.4
      env: TOXENV=py34
    - stage: core
      python: 3.5
      env: TOXENV=py35
    - stage: core
      python: pypy
      env: TOXENV=pypy
    - stage: core
      python: 3.5
      env: TOXENV=flake8


    - stage: contrib
      python: 2.7
      env: TOXENV=py27-django-16
    - stage: contrib
      python: 2.7
      env: TOXENV=py27-django-17
    - stage: contrib
      python: 2.7
      env: TOXENV=py27-django-18
    - stage: contrib
      python: 2.7
      env: TOXENV=py27-django-19
    - stage: contrib
      python: 2.7
      env: TOXENV=py27-django-110


    - stage: contrib
      python: 3.3
      env: TOXENV=py33-django-17
    - stage: contrib
      python: 3.3
      env: TOXENV=py33-django-18

    - stage: contrib
      python: 3.4
      env: TOXENV=py34-django-17
    - stage: contrib
      python: 3.4
      env: TOXENV=py34-django-18
    - stage: contrib
      python: 3.4
      env: TOXENV=py34-django-19
    - stage: contrib
      python: 3.4
      env: TOXENV=py34-django-110

    - stage: contrib
      python: 3.5
      env: TOXENV=py35-django-18
    - stage: contrib
      python: 3.5
      env: TOXENV=py35-django-19
    - stage: contrib
      python: 3.5
      env: TOXENV=py35-django-110
    - stage: contrib
      python: 3.5
      env: TOXENV=py35-django-111-fix
#    - stage: contrib
#      python: 3.5
#      env: TOXENV=py35-django-dev-fix

    - stage: contrib
      python: 2.7
      env: TOXENV=py27-flask-10
    - stage: contrib
      python: 2.7
      env: TOXENV=py27-flask-11
    - stage: contrib
      python: 3.5
      env: TOXENV=py35-flask-10
    - stage: contrib
      python: 3.5
      env: TOXENV=py35-flask-11
    - stage: contrib
      python: 3.5
      env: TOXENV=py35-flask-12

    - stage: contrib
      python: 2.7
      env: TOXENV=py27-celery-3
    - stage: contrib
      python: 2.7
      env: TOXENV=py27-celery-4

    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: sentry
        distributions: "sdist bdist_wheel"
        on:
          tags: true
          repo: sentry/python-raven
        password:
          secure: cG4yO9C+42ljfMlCfIJEgmySUPDCmGht358UaaCum4qchpVaFrjPAvm2sUpr3cFhUmMH+ueUr7LBW2c+lriJyT7wwJlU7vwtECzr5aayUuSwwPpFu98lz8kwQny3KF2caMD15rbjXkDRjh1QXw4ztiuBZq9dLb5WDx3pIKVLLbQ=

script: tox
install:
  - pip install tox wheel codecov "coverage<4"
before_script:
  - pip freeze
after_success:
  - codecov -e DJANGO


